export const GET_ACTIVE_ACCOUNT_TAB = 'ACCOUNT/GET_ACTIVE_ACCOUNT_TAB';
export const CHANGE_ACTIVE_ACCOUNT_TAB = 'ACCOUNT/CHANGE_ACTIVE_ACCOUNT_TAB';
export const CHANGE_SECTION_TITLE_BAR = 'ACCOUNT/CHANGE_SECTION_TITLE_BAR';
export const SET_INPUT_VALUE_FOR_ACCOUNT = 'ACCOUNT/SET_INPUT_VALUE_FOR_ACCOUNT';
export const SAVE_INPUT_VALUE_FOR_ACCOUNT = 'ACCOUNT/SAVE_INPUT_VALUE_FOR_ACCOUNT';
export const CLEAR_INPUT_VALUE_FOR_ACCOUNT = 'ACCOUNT/CLEAR_INPUT_VALUE_FOR_ACCOUNT';