export const GET_ACTIVE_ACCOUNT_TAB = 'GET_ACTIVE_ACCOUNT_TAB';
export const CHANGE_ACTIVE_ACCOUNT_TAB = 'CHANGE_ACTIVE_ACCOUNT_TAB';
export const CHANGE_SECTION_TITLE_BAR = 'CHANGE_SECTION_TITLE_BAR';