export const COLLAPSE_SIDEBAR = 'COLLAPSE_SIDEBAR';
export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAIL = 'GET_USER_DATA_FAIL';
export const REFRESH_TOKEN_REQUEST = 'REFRESH_TOKEN_REQUEST';
export const START_WEBSOCKET = 'START_WEBSOCKET';
export const SET_ACTIVE_PAGE = 'SET_ACTIVE_PAGE';
