export const SET_FIELD_VALUE = 'FUNDING/SET_FIELD_VALUE';
export const DROP_FUNDING_TYPE = 'FUNDING/DROP_FUNDING_TYPE';
export const ADD_SECURITY = 'FUNDING/ADD_SECURITY';
export const REMOVE_SECURITY = 'FUNDING/REMOVE_SECURITY';
export const SET_SECURITY_FIELD_VALUE = 'FUNDING/SET_SECURITY_FIELD_VALUE';

