export const GET_ACTIVE_TAB_PROFILE = 'GET_ACTIVE_TAB_PROFILE';
export const CHANGE_ACTIVE_TAB_PROFILE = 'CHANGE_ACTIVE_TAB_PROFILE';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL';
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const DELETE_USERPIC_REQUEST = 'DELETE_USERPIC_REQUEST';
export const DELETE_USERPIC_SUCCESS = 'DELETE_USERPIC_SUCCESS';
export const DELETE_USERPIC_FAIL = 'DELETE_USERPIC_FAIL';

