import React, { PureComponent } from 'react';

class Footer extends PureComponent {
  render() {
    return (
      <div className="dashboard__footer">
        <p className="main-text-helvetica main-text-helvetica_12">
          Empala Securities, LLC and Empala Network, LLC are wholly-owned subsidiaries of Empala Group, LLC. Equities,
          options, ETF’s, Mutual Funds and bonds are offered to self-directed customers by Empala Securities. Empala
          Securities is a member of the Financial Industry Regulatory Authority (FINRA) and the Securities Investor
          Protection Corporation (SIPC), which protects securities customers of its members up to $500,000 (including
          $250,000 for claims for cash). Explanatory brochures are available upon request or at sipc.org.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          While Empala does not mark up fees or service charges it incurs in servicing clients, it does pass those fees
          through to the client. EMPALA CHARGES A FIXED ANNUAL FEE ON EACH CLIENT'S ACCOUNT. THE FEE IS COLLECTED ON A
          MONTHLY BASIS AS ONE TWELFTH OF THE ANNUAL FEE APPLIED TO THE AVERAGE DAILY VALUE OF THE ACCOUNT IN THE
          RESPECTIVE
          MONTH. THE ANNUAL FEE AT THIS TIME CAN BE FOUND ON OUR Empala Commissions and Fee Schedule. Relevant SEC &
          FINRA
          fees may also apply.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          Empala Securities is currently registered in the following jurisdictions. This is not an offer, solicitation
          of an
          offer, or advice to buy or sell securities, or open a brokerage account in any jurisdiction where Empala
          Securities is not registered. Additional information about your broker can be found by clicking FINRA Public
          Disclosure Program (BrokerCheck).
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          Margin trading involves interest charges and risks, including the potential to lose more than deposited or the
          need to deposit additional collateral in a falling market. Before using margin, customers must determine
          whether
          this type of trading strategy is right for them given their specific investment objectives, experience, risk
          tolerance, and financial situation. For more information please see our Empala Margin Disclosure Statement,
          Empala
          Margin Agreement and FINRA Margin Account Risk Information. These disclosures contain information on Empala
          Securities’ lending policies, interest charges, and the risks associated with margin accounts.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          Investors should consider the investment objectives and unique risk profile of Exchange Traded Funds (ETFs)
          carefully before investing. ETFs are subject to risks similar to those of other diversified portfolios.
          Leveraged
          and Inverse ETFs may not be suitable for all investors and may increase exposure to volatility through the use
          of
          leverage, short sales of securities, derivatives and other complex investment strategies.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          Although ETFs are designed to provide investment results that generally correspond to the performance of their
          respective underlying indices, they may not be able to exactly replicate the performance of the indices
          because of
          expenses and other factors. A prospectus contains this and other information about the ETF and should be read
          carefully before investing. Customers should obtain prospectuses from issuers and/or their third party agents
          who
          distribute and make prospectuses available for review. ETFs are required to distribute portfolio gains to
          shareholders at year end. These gains may be generated by portfolio rebalancing or the need to meet
          diversification requirements. ETF trading will also generate tax consequences. Additional regulatory guidance
          on
          Exchange Traded Products can be found by clicking ETF Disclosure Statement.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          Options transactions may involve a high degree of risk. Please review the options disclosure document entitled
          Characteristics and Risks of Standardized Options available through our Disclosure Library or theocc.com to
          learn
          more about the risks associated with options trading.
          Third party advertising and information provided for product features, communications, and communications
          emanating from social media communities, market prices, data and other information available through Empala
          Group,
          LLC, Empala Securities, LLC or Empala Network, LLC are meant for informational purposes only and are not
          intended
          as an offer or solicitation for the purchase or sale of any financial instrument or as an official
          confirmation of
          any transaction. The information provided is not warranted as to completeness or accuracy and is subject to
          change
          without notice. The Empala website provides its users links to social media sites and email. The linked social
          media and email messages are pre-populated. However, these messages can be deleted or edited by users, who are
          under no obligation to send any pre-populated messages. Any comments or statements made herein do not reflect
          the
          views of Empala Group, LLC, Empala Securities, LLC or Empala Network LLC, or any of their subsidiaries or
          affiliates.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          Investors should be aware that system response, execution price, speed, liquidity, market data, and account
          access
          times are affected by many factors, including market volatility, size and type of order, market conditions,
          system
          performance, and other factors.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          All investments involve risk and the past performance of a security, or financial product does not guarantee
          future results or returns. Keep in mind that while diversification may help spread risk it does not assure a
          profit, or protect against loss, in a down market. There is always the potential of losing money when you
          invest
          in securities, or other financial products. Investors should consider their investment objectives and risks
          carefully before investing.
        </p>
        <p className="main-text-helvetica main-text-helvetica_12">
          Check the background of Empala Group, LLC and Empala Securities, LLC on FINRA Public Disclosure Program
          (BrokerCheck).
        </p>
        <ul className="list-horizontal">
          <li className="list-horizontal__item">
            <a className="list-horizontal__link" href="">Empala Master Customer Agreement</a>
          </li>
          <li className="list-horizontal__item">
            <a className="list-horizontal__link" href="">Empala Securities Use and Risk Disclosures</a>
          </li>
          <li className="list-horizontal__item">
            <a className="list-horizontal__link" href="">Disclosure Library</a>
          </li>
          <li className="list-horizontal__item">
            <a className="list-horizontal__link" href="">Empala Privacy Policy</a>
          </li>
          <li className="list-horizontal__item">
            <a className="list-horizontal__link" href="">Contact Us</a>
          </li>
          <li className="list-horizontal__item">
            <a className="list-horizontal__link" href="">FAQ</a>
          </li>
        </ul>
        <div className="dashboard__copyright">© 2018 Empala. All rights reserved.</div>
      </div>
    );
  }
}

export default Footer;
