export const widgetAttributes = {
  overview_social_capital: {
    id: 'overview_social_capital',
    title: 'Social capital',
    icon: 'groups',
    col: 3,
    height: 390,
    padding_left: 5,
    padding_right: 35,
  },
  overview_financial_capital_exposure: {
    id: 'overview_financial_capital_exposure',
    title: 'Financial capital',
    icon: 'community',
    col: 5,
    height: 390,
    padding_left: 15,
    padding_right: 15,
  },
  overview_environmental_capital: {
    id: 'overview_environmental_capital',
    title: 'Environmental capital',
    icon: 'environmental',
    col: 4,
    height: 390,
    padding_left: 15,
    padding_right: 15,
  },
  active_orders: {
    id: 'active_orders',
    title: 'Active orders',
    col: 5,
    height: 290,
    padding_left: 15,
    padding_right: 15,
  },
  overview_working_deals: {
    id: 'overview_working_deals',
    title: 'Working deals',
    col: 3,
    height: 290,
    padding_left: 5,
    padding_right: 14,
  },
  overview_deals_development: {
    id: 'overview_deals_development',
    title: 'Deal developments',
    col: 3,
    height: 290,
    padding_left: 15,
    padding_right: 14,
  },
  dashboard_orders: {
    id: 'dashboard_orders',
    title: 'Orders',
    col: 12,
    height: 224,
    dots: true,
  },
  dashboard_fills: {
    id: 'dashboard_fills',
    title: 'Fills/cancels',
    col: 12,
    height: 222,
    dots: true,
  },
  dashboard_community_league: {
    id: 'dashboard_community_league',
    title: 'Community league',
    col: 5,
    col_md: 12,
    height: 439,
    assetAmountRange: true,
    info: true,
    switcher: {
      labels: ['Empala network', 'Your network'],
    },
  },
};
export const tableHeaders = {
  dashboard_cash: {
    id: 'dashboard_cash',
    title: 'Currency and money markets fund balance',
    col: 12,
    height: 'auto',
    localFX: true,
    dots: true,
    headers: [
      'Date',
      'Symbol',
      'Sec name',
      'Sec ID',
      'Qty',
      'Avg price',
      'Exec fees',
      'Reg fees',
      'Notional',
      'Curr',
      'Curr. effect',
      'EMARA balance',
      'USD balance',
      'GBP balance',
      'EUR balance',
      'Trade conf. link',
      'Comments',
    ],
    attrs: {
      align: [
        'left',
        'left',
        'left',
        'left',
        'right',
        'right',
        'right',
        'right',
        'right',
        'left',
        'right',
        'right',
        'right',
        'right',
        'right',
        'center',
        'center',
      ],
      width: [
        '93px',
        '60px',
        '178px',
        '78px',
        '90px',
        '90px',
        '102px',
        '88px',
        '108px',
        '45px',
        '106px',
        '126px',
        '124px',
        '128px',
        '114px',
        '110px',
        '78px',
      ],
    },
  },
  dashboard_watchlist: {
    id: 'dashboard_watchlist',
    title: 'Watchlists',
    col: 12,
    height: 429,
    dots: true,
    headers: [
      'Sec name',
      'Symbol',
      'Curr',
      'Last P',
      'Bid SZ',
      'Bid',
      'Offer',
      'Off SZ',
      'Day volume',
      'Sentiment',
      'ES CH',
      'P/E ratio',
      'Sec ID',
      'Rating',
    ],
    attrs: {
      align: [
        'left',
        'left',
        'center',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'center',
        'center',
        'center',
        'right',
        'center',
      ],
      width: [
        '210px',
        '107px',
        '75px',
        '138px',
        '114px',
        '114px',
        '110px',
        '110px',
        '125px',
        '110px',
        '88px',
        '88px',
        '145px',
        '190px',
      ],
      sortable: [
        false,
        true,
      ],
    },
  },
  dashboard_orders: {
    id: 'dashboard_orders',
    title: 'Orders',
    height: 164,
    dots: true,
    headers: [
      'Sec name',
      'Symbol',
      'Curr',
      'Price',
      'Order Q',
      'Fill Q',
      'Rem Q',
      'Notional',
      'Commission',
      'Distance (%)',
      'Start date',
      'O/C/T',
    ],
    attrs: {
      align: [
        'left',
        'left',
        'left',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'center',
        'center',
      ],
      width: [
        '230px',
        '125px',
        '86px',
        '138px',
        '150px',
        '150px',
        '135px',
        '130px',
        '125px',
        '120px',
        '130px',
        '200px',
      ],
      sortable: [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
    },
  },
  dashboard_fills: {
    id: 'dashboard_fills',
    title: 'Fills/cancels',
    height: 162,
    dots: true,
    headers: [
      'Sec name',
      'Symbol',
      'Curr',
      'Price',
      'Order Q',
      'Fill Q',
      'Notional',
      'Exec fees',
      'Reg fees',
      '$ proceeds',
      'Start date',
      'O/C/T',
    ],
    attrs: {
      align: [
        'left',
        'left',
        'left',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'center',
        'center',
      ],
      width: [
        '230px',
        '125px',
        '86px',
        '138px',
        '150px',
        '150px',
        '135px',
        '130px',
        '125px',
        '120px',
        '130px',
        '200px',
      ],
      sortable: [
        false,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
      ],
    },
  },
  dashboard_positions_portfolio: {
    id: 'dashboard_positions_portfolio',
    title: 'Position portfolio',
    col: 12,
    dots: true,
    localFX: true,
    headers: [
      'Start date',
      'Symbol',
      'Sec name',
      'Sec ID',
      'Category',
      'Country',
      'Curr',
      'Ann CF%',
      'Carry',
      'Ann Ret',
      'VAR Cont',
      'Avg Price',
      'Quantity',
      'M2M',
      'Notional',
      'Tot % Chg',
      'Tot P&L',
      'Day % Chg',
      'Day P&L',
    ],
    attrs: {
      width: [
        '98px',
        '65px',
        '125px',
        '70px',
        '90px',
        '65px',
        '48px',
        '65px',
        '45px',
        '65px',
        '80px',
        '78px',
        '62px',
        '80px',
        '80px',
        '80px',
        '80px',
        '80px',
        '75px',
      ],
      align: [
        'left',
        'left',
        'left',
        'right',
        'left',
        'left',
        'left',
        'left',
        'left',
        'left',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
        'right',
      ],
      sortable: [
        true,
        true,
        false,
        true,
        false,
        true,
        true,
        false,
        false,
        true,
      ],
    },
  },
  overview_financial_capital_exposure: {
    id: 'overview_financial_capital_exposure',
    height: 200,
    headers: [
      'Exposure',
      'Value',
      'D % ch',
    ],
    attrs: {
      align: [
        'left',
        'right',
        'right',
      ],
      width: [
        '125px',
        '95px',
        '50px',
      ],
      sortable: [
      ],
    },
  },
  overview_financial_capital_allocation: {
    id: 'overview_financial_capital_allocation',
    height: 200,
    headers: [
      'Allocation',
      'Domestic',
      'Foreign',
    ],
    attrs: {
      align: [
        'left',
        'right',
        'right',
      ],
      width: [
        '120px',
        '105px',
        '85px',
      ],
      sortable: [
      ],
    },
  },
  overview_financial_capital_performance_st: {
    id: 'overview_financial_capital_performance_st',
    title: 'Financial capital performance',
    col: 5,
    padding_left: 10,
    headers: [
      'ST performance',
      '% change',
      'Vs indexes',
    ],
    attrs: {
      align: [
        'left',
        'right',
        'right',
      ],
      width: [
        '115px',
        '75px',
        '80px',
      ],
      sortable: [
      ],
    },
  },
  overview_financial_capital_performance_lt: {
    id: 'overview_financial_capital_performance_lt',
    title: 'Financial capital performance',
    col: 5,
    headers: [
      'LT Performance',
      '% change',
      'Vs indexes',
    ],
    attrs: {
      align: [
        'left',
        'right',
        'right',
      ],
      width: [
        '120px',
        '105px',
        '85px',
      ],
      sortable: [
      ],
    },
  },
  overview_social_capital_network: {
    id: 'overview_social_capital_network',
    title: 'Social capital',
    height: 200,
    headers: [
      'Network',
      'No.',
    ],
    attrs: {
      align: [
        'left',
        'right',
      ],
      width: [
        '185px',
        '75px',
      ],
      sortable: [
      ],
    },
  },
  overview_social_capital_positioning: {
    id: 'overview_social_capital_positioning',
    height: 200,
    headers: [
      'Positioning',
      '%ile',
    ],
    attrs: {
      align: [
        'left',
        'right',
      ],
      width: [
        '130px',
        '45px',
      ],
      sortable: [
      ],
    },
  },
  overview_social_capital_get: {
    id: 'overview_social_capital_get',
    headers: [
      'Get',
      'No.',
    ],
    attrs: {
      align: [
        'left',
        'right',
      ],
      width: [
        '185px',
        '75px',
      ],
      sortable: [
      ],
    },
  },
  overview_social_capital_give: {
    id: 'overview_social_capital_give',
    headers: [
      'Give',
      'No.',
    ],
    attrs: {
      align: [
        'left',
        'right',
      ],
      width: [
        '130px',
        '45px',
      ],
      sortable: [
      ],
    },
  },
  overview_environmental_capital_size_growth: {
    id: 'overview_environmental_capital_size_growth',
    height: 200,
    headers: [
      'Size & growth',
      'No.',
    ],
    attrs: {
      align: [
        'left',
        'right',
      ],
      width: [
        '180px',
        '90px',
      ],
      sortable: [
      ],
    },
  },
  overview_environmental_capital_opinions: {
    id: 'overview_environmental_capital_opinions',
    headers: [
      'Opinions',
      'No.',
    ],
    attrs: {
      align: [
        'left',
        'right',
      ],
      width: [
        '180px',
        '90px',
      ],
      sortable: [
      ],
    },
  },
  active_orders: {
    id: 'active_orders',
    title: 'Active orders',
    height: 220,
    dots: true,
    headers: [
      'Security & symbol',
      'Price',
      'Qty',
      'Notional',
      'Diff %',
    ],
    attrs: {
      align: [
        'left',
        'right',
        'right',
        'right',
        'right',
      ],
      width: [
        '230px',
        '115px',
        '75px',
        '95px',
        '74px',
      ],
      sortable: [
        true,
      ],
    },
  },
  overview_working_deals: {
    id: 'overview_working_deals',
    title: 'Working deals',
    height: 220,
    dots: true,
    headers: [
      'Description',
      'Amount',
      'Clearing price',
      'Diff %',
      'Status',
    ],
    attrs: {
      align: [
        'left',
        'right',
        'right',
        'right',
        'left',
      ],
      width: [
        '185px',
        '75px',
        '90px',
        '55px',
        '60px',
      ],
      sortable: [
      ],
    },
  },
  overview_deals_development: {
    id: 'overview_deals_development',
    title: 'Deals development',
    height: 220,
    headers: [
      'Description',
      'Date',
      'Update type',
      'Diff %',
    ],
    attrs: {
      align: [
        'left',
        'center',
        'left',
        'right',
      ],
      width: [
        '210px',
        '135px',
        '130px',
        '77px',
      ],
      padding: [
        null,
        null,
        null,
        '0 30px 0 0',
      ],
      sortable: [
      ],
    },
  },
  dashboard_community_league: {
    id: 'dashboard_community_league',
    title: 'Community league',
    height: 336,
    dots: true,
    headers: [
      'Rank',
      'Name',
      'Ann % R',
      'Total % R',
      'Total $ Ret',
      'Total $ Val',
      '1YR % R',
      '3M % R',
      '1M % R',
    ],
    attrs: {
      align: [...Array(2).fill('left'), ...Array(7).fill('right')],
      width: [
        '7%',
        '21%',
        '9%',
        '9%',
        '12%',
        '15%',
        '9%',
        '9%',
        '9%',
      ],
      sortable: [...Array(2).fill(false), ...Array(7).fill(true)],
    },
  },
};
